### ISSUE TITLE
Display the U# class name on UdonBehaviour editor element header

### ISSUE THREAD

**Issue by Varneon** [Varneon/VUdon-Udonity#22]
Suggested by @techanon

**Comment by techanon** [comment]
You can get the name of the UdonSharp type by calling `UdonBehaviour.GetProgramVariable("__refl_typename")` during runtime.

**Comment by Varneon** [comment]
Cache the program index and name out parameter during initialization by calling https://github.com/Varneon/VUdon-Udonity/blob/5168f1efbc508cd2199c1c0eca689bdcac11cf15/Packages/com.varneon.vudon.udonity/Runtime/Udon%20Programs/Internal/UdonProgramDataStorage.cs#L30

during the initialization of the [`UdonBehaviourEditor`](https://github.com/Varneon/VUdon-Udonity/blob/main/Packages/com.varneon.vudon.udonity/Runtime/Udon%20Programs/Editor%20Elements/UdonBehaviourEditor.cs) https://github.com/Varneon/VUdon-Udonity/blob/5168f1efbc508cd2199c1c0eca689bdcac11cf15/Packages/com.varneon.vudon.udonity/Runtime/Udon%20Programs/Editor%20Elements/UdonBehaviourEditor.cs#L23

If the cached program index is < 0, the dropdown menu item `Open In UdonMonitor` can be disabled

**Comment by Varneon** [comment]
Slight change of plans: the original UdonSharp proxy behaviour will get reconstructed during runtime.

![image](https://github.com/Varneon/VUdon-Udonity/assets/26690821/e04f4de1-40cb-4744-b8ed-aaccdc96481a)
