### ISSUE TITLE
Hierarchy's iterator crashes Udonity if hierarchy is empty

### ISSUE THREAD

**Issue by Varneon** [Varneon/VUdon-Udonity#51]

**Comment by techanon** [comment]
I'm experiencing this crash. Is there a known work around to this or a better explanation as to what the crash means?

**Comment by Varneon** [comment]
> I'm experiencing this crash (w/ 2022.3.6 + pre-alpha.7). Is there a known work around to this

Just make sure that Udonity has something to inspect on build by either adding a [`UdonityRootInclusionDescriptor`](https://github.com/Varneon/VUdon-Udonity/wiki/How-to-Add-Objects-to-Udonity's-Hierarchy-for-Inspection#add-udonityrootinclusiondescriptor-component-to-the-gameobject) to a hierarchy tree, or by [adding a root object to the list of inspected roots](https://github.com/Varneon/VUdon-Udonity/wiki/How-to-Add-Objects-to-Udonity's-Hierarchy-for-Inspection#add-transforms-to-udonity-editors-roots-array).

> or a better explanation as to what the crash means? It happens immediately when I enter playmode in editor.

Udonity has an [internal hierarchy iterator](https://github.com/Varneon/VUdon-Udonity/blob/2d0e43d85d20a74487f3185981844d11332c2f1d/Packages/com.varneon.vudon.udonity/Runtime/Udon%20Programs/Windows/Hierarchy.cs#L323-L348) for scanning changes, _e.g. was an object deleted, active state changed, etc._ I had never used Udonity without any objects to inspect, thus I never ran into this bug in internal testing, resulting in the possibility of an empty hierarchy being completely overlooked.

This bug is expected to be fixed in **pre-alpha.8**


Hope this helps!

- Varneon

**Comment by techanon** [comment]
Right, that make sense. I forgot about that part. Been a while since I used this, so I just added it to the scene assuming it would default to making all scene root objects available on the list by default.
